### ISSUE TITLE
Error response received from upstream api

### ISSUE THREAD

**Issue by helmut72** [marcopaganini/quotes-exporter#4]
Is this still working? When opening your example URL, log output is:

```
2023/05/04 20:33:55 URL: /price?symbols=VTIAX
2023/05/04 20:33:55 Error looking up VTIAX: code: remote-error, detail: code: remote-error, detail: error response recieved from upstream api
```

Thank you.

**Comment by marcopaganini** [comment]
You're correct. It's broken. Thanks for bringing it to my attention. This message is coming from the upstream library. I'll take a look.

**Comment by umatare5** [comment]
I checked that Y-Finance API v7 invoked by finance-go v1.0.0 has been stopped. In response to this case, finance-go created new release v1.1.0 that downgraded the API to v6.

https://github.com/piquette/finance-go/releases/tag/v1.1.0

- Full comparison https://github.com/piquette/finance-go/compare/v1.0.0...v1.1.0 contains https://github.com/piquette/finance-go/pull/27

**Comment by marcopaganini** [comment]
Oh nice, thanks. When I checked only v1.0.0 was available. Approving and merging.

**Comment by umatare5** [comment]
Thanks!

**Comment by helmut72** [comment]
Thank you. I wanted to try it today, but still doesn't work.

**Comment by marcopaganini** [comment]
Oh bummer. I tested this but now it's broken again?!? Let me take a look. Maybe it's time to change the library. It's a shame that there's no reasonable, free way to fetch stock prices.

**Comment by marcopaganini** [comment]
So I'm having a hard time finding an API that 1) Is free, 2) Is reliable, and 3) Allows a reasonable number of calls per day on the free tier. I found alphavantage which appears to be good, but they're limited to 500 calls a day, which would be exhausted rather quickly (~ one request every 3h).

From a brief read of their documentation, it appears that they consider every *single* request a call (counting towards the 500 calls per day limit), which would limit things even further.

I'm still looking, but please do share if you know of a good finance API that meets the above criteria.

**Comment by helmut72** [comment]
I've searched in your used Library:
<https://github.com/piquette/finance-go/issues/25>

Then found this one:
<https://stackoverflow.com/questions/76065035/yahoo-finance-v7-api-now-requiring-cookies-python>

Then I've tried this in a Linux Bash:

```
curl -c cookie.txt "https://fc.yahoo.com"
crumb=$(curl -s -b cookie.txt "https://query2.finance.yahoo.com/v1/test/getcrumb")
curl -s -b cookie.txt "https://query2.finance.yahoo.com/v7/finance/quote?symbols=AAPL&crumb=$crumb" |jq
```

Works! Of course I don't know how long...

**Comment by marcopaganini** [comment]
Yeah I think anything based on yahoo finance is doomed to fail. The API has
been more than deprecated. One simple option (I may implement it quickly)
is to use stonks.scd31.com. I'll probably release an interim version with
support for that.

**Comment by marcopaganini** [comment]
I just submitted https://github.com/marcopaganini/quotes-exporter/commit/58f6d115c37e58f960f6008f873fa6f6214ec536 which switches the quotes provider to stonks.scd31.com. This has the unfortunate side effect of not supporting mutual funds, but at least (for now) it avoids the hassle of users having to register and maintain API keys and deal with quota issues from most financial API providers out there.

**Comment by marcopaganini** [comment]
@helmut72 please let me know if it works for you now.

**Comment by helmut72** [comment]
Works now, thank you.
